CREATE TABLE EXERCISE (
    exercise_id SERIAL PRIMARY KEY,
    exercise_name VARCHAR(100),
    upper_back VARCHAR(100),
    middle_back VARCHAR(100),
    lower_back VARCHAR(100),
    upper_chest VARCHAR(100),
    middle_chest VARCHAR(100),
    lower_chest VARCHAR(100),
    upper_abs VARCHAR(100),
    lower_abs VARCHAR(100),
    obliques VARCHAR(100),
    upper_trap VARCHAR(100),
    lower_trap VARCHAR(100),
    quads  VARCHAR(100),
    hamstrings  VARCHAR(100),
    calves  VARCHAR(100),
    upper_glutes  VARCHAR(100),
    middle_glutes  VARCHAR(100),
    lower_glutes  VARCHAR(100),
    biceps  VARCHAR(100),
    triceps  VARCHAR(100)
    )